builders: allow tbot.ini without BUILDHOST_local section
prevent error
configparser.NoSectionError: No section: 'BUILDHOST_local'

if no BUILDHOST_local section is in tbot.ini

Fixes: b46a4b541107 ("builders: introduce local machine as builder")

Signed-off-by: Heiko <hs@denx.de>